name: npm-publish
on:
  push:
    branches:
      - master # Change this to your default branch
jobs:
  npm-publish:
    name: npm-publish
    runs-on: ubuntu-latest
    steps:
      - name: 切换仓库
        uses: actions/checkout@master
      - name: 准备Node环境
        uses: actions/setup-node@master
        with:
          node-version: 12.13.0
      - name: 安装依赖以及编译
        run: npm i && npm run build
      - name: 推送到NPM
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_AUTH_TOKEN }}
  cnpm-sync:
    name: cnpm-sync
    needs: npm-publish
    runs-on: ubuntu-latest
    steps:
      - name: 同步cnpm仓库
        uses: fjogeleit/http-request-action@master
        with:
          # 需要把‘express’换成你的包名，谨记
          url: "https://npmmirror.com/sync/enjoy-project-tool"
          timeout: 50000
          method: GET
